name: 部署到抱抱脸空间

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' 
    
jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      token-set: ${{ steps.check-key.outputs.defined }}
    steps:
      - id: check-key
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        if: "${{ env.HF_TOKEN != '' }}"
        run: echo "defined=true" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: [check-secret]
    if: needs.check-secret.outputs.token-set == 'true'
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO: ${{ secrets.HF_REPO }}
      HF_USER: ${{ secrets.HF_USER }}
      TZ: Asia/Shanghai
    steps:
      - name: 检测仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: 生成部署日志
        run: |
          mkdir -p docs
          export TZ=Asia/Shanghai
          START_TIME=$(date '+%Y-%m-%d %H:%M:%S')
          cat > docs/deploy_log_$(date '+%Y%m%d').html << EOF
          <!DOCTYPE html>
          <html lang="zh-CN">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>部署日志 - $(date '+%Y-%m-%d')</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                      margin: 0;
                      padding: 20px;
                      color: #333;
                      line-height: 1.6;
                      background-color: #f5f5f5;
                  }
                  .container {
                      max-width: 800px;
                      margin: 0 auto;
                      background: #fff;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  h1 {
                      color: #2c3e50;
                      text-align: center;
                      margin-bottom: 30px;
                      padding-bottom: 10px;
                      border-bottom: 2px solid #eee;
                  }
                  .log-entry {
                      background: #f8f9fa;
                      padding: 20px;
                      margin: 15px 0;
                      border-radius: 8px;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.05);
                  }
                  .log-entry p {
                      margin: 10px 0;
                  }
                  .success { color: #28a745; }
                  .duration { color: #0066cc; }
                  .timestamp { color: #666; }
                  .footer {
                      text-align: center;
                      margin-top: 30px;
                      padding-top: 20px;
                      border-top: 1px solid #eee;
                      color: #666;
                  }
                  .footer a {
                      color: #0366d6;
                      text-decoration: none;
                  }
                  .footer a:hover {
                      text-decoration: underline;
                  }
                  @media (max-width: 600px) {
                      body { padding: 10px; }
                      .container { padding: 15px; }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>部署日志</h1>
                  <div class="log-entry">
                      <p><strong>部署时间:</strong> <span class="timestamp">${START_TIME}</span></p>
                      <p><strong>分支:</strong> ${GITHUB_REF#refs/heads/}</p>
                      <p><strong>提交SHA:</strong> ${GITHUB_SHA}</p>
                      <p><strong>触发事件:</strong> ${GITHUB_EVENT_NAME}</p>
                      <p><strong>工作流程:</strong> <a href="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" target="_blank">查看详情</a></p>
                      <p><strong>状态:</strong> <span class="success">✓ 成功</span></p>
                  </div>
                  <div class="footer">
                      <p><a href="https://linux.do" target="_blank">LINUX DO</a></p>
                  </div>
              </div>
          </body>
          </html>
          EOF

          if [ ! -f docs/index.html ]; then
            cat > docs/index.html << EOF
          <!DOCTYPE html>
          <html lang="zh-CN">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>部署日志索引</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                      margin: 0;
                      padding: 20px;
                      color: #333;
                      line-height: 1.6;
                      background-color: #f5f5f5;
                  }
                  .container {
                      max-width: 800px;
                      margin: 0 auto;
                      background: #fff;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  h1 {
                      color: #2c3e50;
                      text-align: center;
                      margin-bottom: 30px;
                      padding-bottom: 10px;
                      border-bottom: 2px solid #eee;
                  }
                  .log-list {
                      list-style: none;
                      padding: 0;
                  }
                  .log-list li {
                      margin: 10px 0;
                      padding: 15px;
                      background: #f8f9fa;
                      border-radius: 8px;
                      transition: all 0.3s ease;
                  }
                  .log-list li:hover {
                      background: #e9ecef;
                      transform: translateX(5px);
                  }
                  .log-list a {
                      text-decoration: none;
                      color: #0366d6;
                      display: block;
                  }
                  .footer {
                      text-align: center;
                      margin-top: 30px;
                      padding-top: 20px;
                      border-top: 1px solid #eee;
                      color: #666;
                  }
                  .footer a {
                      color: #0366d6;
                      text-decoration: none;
                  }
                  .footer a:hover {
                      text-decoration: underline;
                  }
                  @media (max-width: 600px) {
                      body { padding: 10px; }
                      .container { padding: 15px; }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>部署日志索引</h1>
                  <ul class="log-list">
          EOF
          fi

          sed -i "/<ul class=\"log-list\">/a \        <li><a href=\"deploy_log_$(date '+%Y%m%d').html\">$(date '+%Y-%m-%d') 部署日志</a></li>" docs/index.html

          if ! grep -q "</body>" docs/index.html; then
            echo "                  </ul>" >> docs/index.html
            echo "                  <div class=\"footer\">" >> docs/index.html
            echo "                      <p><a href=\"https://linux.do\" target="_blank">LINUX DO</a></p>" >> docs/index.html
            echo "                  </div>" >> docs/index.html
            echo "              </div>" >> docs/index.html
            echo "          </body>" >> docs/index.html
            echo "          </html>" >> docs/index.html
          fi

      - name: 提交部署日志
        run: |
          git add docs/
          git commit -m "Update deployment logs [skip ci]" || echo "No changes to commit"
          git push origin ${GITHUB_REF_NAME}

      - name: 部署到Hugging Face
        run: |
          rm -rf .git
          echo "/docs" > .gitignore
          echo "/.github" >> .gitignore
          echo "---" > temp_readme.md
          echo "title: API" >> temp_readme.md
          echo "emoji: 📊" >> temp_readme.md
          echo "colorFrom: purple" >> temp_readme.md
          echo "colorTo: gray" >> temp_readme.md
          echo "sdk: docker" >> temp_readme.md
          echo "app_port: 8080" >> temp_readme.md
          echo "---" >> temp_readme.md
          cat README.md >> temp_readme.md
          mv temp_readme.md README.md
          git init --initial-branch=main
          git lfs track "*.ttf"
          git add .
          git commit -m "GitHub deploy: ${GITHUB_SHA}"
          git push --force https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${HF_REPO} main
